### ISSUE TITLE
Is there a way to access the final font-size values for use elsewhere in CSS?

### ISSUE THREAD

**Issue by drdogbot7** [davidhellmann/tailwindcss-fluid-type#10]
For instance with the core fontSize plugin, I can do this:

```css
:root {
 --foo: theme('fontSize.lg');
}
```

...but since the fluid type plugin calculates the final values at build time, that doesn't work.

I realize I could use @apply in a lot of cases, but it would be useful to have direct access to the values.
