### ISSUE TITLE
Best practices to add the fluid-type settings to “prose” sections of a page (official Tailwind CSS Typography plugin)?

### ISSUE THREAD

**Issue by MichaelvanLaar** [davidhellmann/tailwindcss-fluid-type#22]
This is a question from a Tailwind CSS noob and fluid type noob. So, sorry if it’s stupid.

I love the tailwindcss-fluid-type plugin since it makes using a fluid scales for font sizes a no-brainer in Tailwind CSS. But for certain parts of pages I need the [Typography plugin](https://tailwindcss.com/docs/typography-plugin), whenever I have to include “unstyled” content from a typical CMS WYSIWYG editor field. A container element with the `prose` class usually works fine.

I have to adapt the default styling of the Typography plugin to the rest of the site anyway. So this is not the point.

But to include fluid type settings, I would copy the final `font-size` definitions from the rendered CSS file and paste them into the settings of the Typography plugin. For example, I would copy the `clamp` function of a `.text-base` selector and include it as `font-size` for `prose-base` in my configuration, like so:

```javascript
module.exports = {
  theme: {
    extend: {
      typography: {
        DEFAULT: {
          css: {
            'font-size':
              'clamp(1.125rem, calc(1.125rem + ((1.25 - 1.125) * ((100vw - 20rem) / (96 - 20)))), 1.25rem)',
          },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('tailwindcss-fluid-type'),
  ],
}
```

And then the same for the `prose-sm`, `prose-lg`, `prose-xl` and `prose-2xl`.

It works. And since the Typography plugin uses relative font-sizes, it also works nicely out of the box for all elements like headlines, etc.

But it is neither an elegant nor a flexible solution – especially not, if I change the settings of the fluid-type plugin later on, and then will have to manually adapt all the typography plugin settings to the new `clamp` outputs.

Is there a better way? Or any best practices?

**Comment by MichaelvanLaar** [comment]
“Solved” this in my current project with the above mentioned fluid type / zoom feature:

- Uninstalled the tailwindcss-fluid-type plugin.
- [Added a proper font-size definition for the HTML element.](https://github.com/MichaelvanLaar/mvlkss/blob/d9584524733832c9cabd3bccbca4c9ff09dfcb82/src/css/main.css#L14-L22)

```css
@layer base {
  html {
    /* Implement a fluid font size based on viewport width with a minimum size
       of 16px and a maximum of 22px. This also affects all relative size
       specifications which are directly or indirectly based on the base font
       size. The result is a zoom effect of the whole layout. */
    font-size: clamp(1.00rem, calc(0.86rem + 0.55vw), 1.38rem);
  }
}
```

Yes, this does not only affect the font sizes, but all relative size specifications. This is intended. Text, the `prose` styles, margins, paddings, row gaps, etc. will grow automatically – within limits.
